### ISSUE TITLE
how to choose the python version?

### ISSUE THREAD

**Issue by congcong009** [andrebienemann/quant#1]
This is the greatest build I ever use before for the quant jupyter! Excelent job.

A quick question is that the last build showed the python version as below:
3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]

But in some case I may need to use 3.8 instead. How to config the python version during the build? Or which build refer to the 3.8v python?  

I try to install a new kernel manually but the environment is not quite stable after all. I meet the kernel restart for serveal time and have no idea to fix this.

```
Kernel Restarting
The kernel for */*.ipynb appears to have died. It will restart automatically.
```

**Comment by andrebienemann** [comment]
Hey, thank you! Very much appreciate your feedback.

At the current moment, the images are built and published for Python 3.10

However, by the sound of it, you build your own images from this repository which should make it easy for you to get any version of Python by referring to a different base image that is shipped with apt for package management and provides the desired version of Python.

Creating your own kernel is also a possibility, but I would advise you against this approach because it's essentially more work and hassle than simply swapping the base image.

I can take on your input and parametrise Dockerfile for building images with Python versions different from the upstream.

**Comment by andrebienemann** [comment]
It's now possible to specify the version of Python you wish to build your environment on top of.

For instance, if you need an image with Python 3.8, execute the command as shown below.

```bash
make build VERSION=3.8-slim
```

To see other available versions, refer to the [registry](https://hub.docker.com/_/python/tags).

**Comment by congcong009** [comment]
Super! Thanks for quick reply and update. 

I totally agree with the approach not to add kernel. So that is why I may need to build a new image. 

By the way. Do you have any plan to upgrade this image to JupyterHub? :)

**Comment by congcong009** [comment]
Indeed, if only for personal use, the current image is sufficient. I have implemented a quantitative framework by myself, and in the team, it needs to be used collaboratively by multiple people. 

In the development phase, the current version is sufficient. I have already completed most of the development and testing based on it. The next step is to deploy it in a collaborative environment, so JupyterHub is a more reasonable choice. 

When customizing the compilation, I mainly added database drivers, some self-implemented libraries, and of course, some ready-made libraries for email, logging others such as tqdm, clickhouse_driver, retrying, seaborn, statsmodels, pika, tornado, celery, psycopg2-binary, redmail, zenlog and so on.

Initially, I based my compilation on your image, but considering optimization and deployment issues, I have now started a fresh compilation.

**Comment by andrebienemann** [comment]
Thanks for sharing your use case. Good to know what people are up to.

When extending this image with JupyterHub, keep in mind that JupyterHub is a management layer above JupyterLab. It spawns single-user notebooks which can either run in isolated containers or the same environment. The first one is arguably the preferred approach while the second one is easier to set up but also comes with downsides.

I will explain those downsides since you're seemingly choosing the second approach and may want to know the implications. First of all, there may be interference between users and conflicts in system packages, Python libraries and environment variables. The other problem with shared environments is that resources with no utilisation limits tend to be abused. When someone realises they can use all available cores or allocate the entire RAM, they almost certainly will do so. That's why isolated containers with granular control and isolation per design shine here.

I may write a Helm chart for multitenant deployments on Kubernes with JupyterHub and the Quant image at some point.

**Comment by congcong009** [comment]
You are absolutely right! In fact, I have two options:

1. Use JupyterHub to achieve team sharing, inculding sharing quotation research environment, database config connection, and message queue subscriptions. From a higher perspective, both hardware and computing are resources. Utilizing them in a competitive manner can maximize resource utilization and enable computation and backtesting results to be reused. However, it can also lead to the allocation issues you mentioned. JupyterHub, as a management system, addresses resource management, access authorization, and environment independence. The drawbacks I find are mainly related to the difficulty of K8s deployment and maintenance, as well as the hardware resource consumption of the management platform itself.

2. Another lighter-weight approach is to deploy containers based on the your image according to each user. For example, if I have five researchers, I would deploy five containers with different port and jupyterlab account configurations for them to use independently. Currently, I am trying this approach. However, if the team increases, then I will have to consider using JupyterHub for next stage.
